INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '1', 'Activo');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11', 'Activo Corriente ');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01', 'Efectivo Caja y Banco');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-01', 'Banco Popular');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-02', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-03', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-04', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-05', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-06', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-07', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-01-08', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02', 'Banco de Reservas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02-01', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02-02', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02-03', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02-04', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02-05', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02-06', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-02-07', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03', 'Banco BHD Leon');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03-01', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03-02', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03-03', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03-04', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03-05', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03-06', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-03-07', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04', 'Scotiabak');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04-01', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04-02', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04-03', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04-04', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04-05', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04-06', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-04-07', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05', 'Santa Cruz');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05-01', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05-02', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05-03', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05-04', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05-05', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05-06', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-05-07', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06', 'Cooperativa de Ahorros y Prestamos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06-01', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06-02', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06-03', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06-04', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06-05', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06-06', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-06-07', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07', 'Banco del Progreso');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07-01', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07-02', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07-03', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07-04', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07-05', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07-06', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-07-07', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08', 'Bancos del Extranjero');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-01', 'Cuenta Corriente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-02', 'Cuenta de Ahorros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-03', 'Cuenta de Ahorros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-04', 'Cuenta de Ahorros en Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-05', 'Certificados Financieros en Pesos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-06', 'Certificados Fiancieros en Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-07', 'Certificados Fiancieros en  Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-10-08-08', 'Caja Chica');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-12', 'Cuentas por Cobrar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-12-01', 'Prestamos a los Colegios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-12-02', 'Prestamos a las Comunidades');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-12-03', 'Prestamos a los Profesores');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-12-04', 'Prestamos a los Conserjes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-12-05', 'Prestamos a los Empleados');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-12-06', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-16', 'Inventario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-17', 'Anticipo Impuesto sobre la Renta');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-17-01', 'Seguros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-17-02', 'Placas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-17-03', 'Alquiler');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-17-04', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-18', 'Inversiones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '11-20-18-01', 'Acciones de otra Compania');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12', 'Activos fijos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19', 'Propiedad Planta y Equipos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-01', 'Terreno');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-02', 'Edificio');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-03', 'Depreciacion acumulada en Edificio');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-04', 'Muebles y Equipos de Oficina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-05', 'Depreciacion Acumulada en muebles y Equipos de Oficina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-06', 'Equipo de Transporte');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-07', 'Depreciacion  Equipo de Transporte');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-08', 'Otros Activos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-09', 'Depreciacion Acumulada en Otros Activos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-10', 'Plantas y  Equipos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-11', 'Depreciacion de Otros Equipos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '12-20-19-12', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '13', 'Activos diferidos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '13-20-20', 'Diferidos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '13-20-20-01', 'Gastos de Organizacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '13-20-20-02', 'Mejoras en Propiedad  Arrendada');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '14', 'Otros Activos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '14-20-21', 'Fianza');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '14-20-21-01', 'Fianza');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '14-20-21-02', 'depositos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '14-20-21-03', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '2', 'PASIVOS');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20', 'Pasivos corrientes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-00', 'Sobregiro Bancario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-01', 'Cuentas por pagar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-01-01', 'Casa General');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-01-02', 'Colegios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-01-03', 'Comunidades');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-01-04', 'Cooperativas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-01-05', 'Asociacion de Padres');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-01-06', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-02', 'Prestamos por pagar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-02-01', 'Casa General');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-02-02', 'Colegios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-02-03', 'Comunidades');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-02-04', 'Cooperativas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-02-05', 'Asociacion de Padres');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-02-06', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-06', 'Dividendos declarado por pagar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07', 'Retenciones y acumulaciones por pagar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07-01', 'ARS');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07-02', 'AFP');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07-03', 'Impuestos sobre la renta por pagar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07-04', 'ITBIS');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07-05', 'INFOTEP');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07-06', 'Regalia pascual');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '20-00-07-07', 'Sueldos acumulados por pagar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '21', 'Pasivos a largo plazo');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '21-00-00', 'Hipotecas por pagar a largo plago');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '21-00-01', 'Prestamos por pagar a largo plago');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '22', 'Pasivos diferidos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '22-00-07-01', 'Avance a empleados');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '22-00-07-02', 'Ingresos recibidos por adelantado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '3', 'CAPITAL');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '30', 'Cuenta de capital');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '30-00-01', 'Capital autorizado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '30-00-02', 'Acciones no emitidas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '30-00-03', 'Capital social');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '30-00-04', 'Utilidades o perdidas acumudas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '30-00-05', 'Utilidades o perdidas del periodo');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '30-00-06', 'Resumen de ganancias y/o perdidas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4', 'Ingresos ');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20', 'Cuotas de Inscripcion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-01', 'Pre-matricula');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-02', 'Examen de Admision');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-03', 'Inscripciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-03-01', 'Cuota de Inscripcion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-03-02', 'Enfermeria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-03-03', 'Asociacion de Padres');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-03-04', 'Carmnet Estudiantil');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-03-05', 'Materiales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-03-06', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-04', 'Cuotas Estudiantiles');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-04-01', 'Cuotas Estudiantiles');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-05', 'Ventas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-05-01', 'Uniformes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-05-02', 'Utiles Escolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-05-03', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-06', 'Cafeteria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-06-01', 'Ingresos por Cafeteria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-07', 'Eventos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-07-01', 'Excursiones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-07-02', 'Dia Familiar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-07-03', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-08', 'Aporte por Trabajo  hermanas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-08-01', 'Donaciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-08-02', 'Ayudas Comunidades');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-08-03', 'Otros Ingresos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-09', 'Divisas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-09-01', 'Cambio de Divisas dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-09-02', 'Cambio de Divisas Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-10', 'Otros Ingresos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-10-01', 'Record de NotasCertificadosCartasSellos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-10-02', 'Clinicas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-10-03', 'Microsoft');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-10-04', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-11', 'Mora');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-04-01', 'Recargo por Mora');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-04-02', 'Intereses Bancarios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-13', 'Donaciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-13-01', 'Donaciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-13-02', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-14', 'Subsidios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-14-01', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-15', 'Taller');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-15-01', 'Taller de Corte y Confeccion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '4-20-15-02', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-02', 'Sueldo al Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-02-01', 'Horas Extras');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-02-02', 'Sustituciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-02-03', 'Vacaciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-02-04', 'Regalia de Navidad,');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-03', 'Prestaciones Laborales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-04', 'TSS-Tesoreria de la Seguridad Social');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-05', 'Seguro Medico');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-05-01', 'ARS HUMANO - Suplementario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-05-02', 'ARS-PALI- Complementario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-05-03', 'ARS UNIVERSAL - Complementario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-05-04', 'ARS - SENASA Complementario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-05-05', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-10-05-06', 'Seguro Hnas. Comunidad - Suplementario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-11-02', 'Material Didactico');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-11-02-02', 'Material de Decoracion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-11-02-03', 'Material de uso en clases -MapasLaminasetc.');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-11-03', 'Suscripcion y compra de Libros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-11-03-01', 'Libros de TextosCuentos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-11-03-02', 'Enciclopedias');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-11-04', 'Reparacion Butacas Escritorios Pizarras Armarios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-12-06-05', 'Formacion Permanente');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-12-07', 'Materiales de Oficina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-12-07-01', 'Materiales de Oficina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-13-01', 'Capacitacion al Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-13-01-01', 'Capacitacion al Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-13-01-02', 'Gastos de Actividades y Materiales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-13-09', 'Becas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-13-09-01', 'Gastos de Becas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-14-01', 'Actividades');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-14-01-01', 'Actividades Culturales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-14-01-02', 'Actividades Cientificas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-14-01-03', 'Actividades Religiosas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '5-14-01-04', 'Actividades Deportivas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6', 'Cuentas Gastos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-00-00', 'Gastos Generales y Administrativos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-01', 'Templo y Culto');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-01-01', 'Flores');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-01-02', 'MantelesPurificadoresCorporalesPalias');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-01-03', 'CasullasAlbas y Singulos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-01-04', 'CalizPatena y Copones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-01-05', 'Sagrario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-01-06', 'Custodia');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-06', 'Capacitacion al Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-06-01', 'TalleresCongresoConvivenciaCursos y otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-06-02', 'Licenciaturas Hnas. MaestriaDoctorado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-06-03', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-07', 'Cursillos y  Retiros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-07-01', 'Retiros de Adviento');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-07-02', 'Retiros de Cuaresma');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-07-03', 'Convivencia Alumnos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-07-04', 'Convice   ConvivenciaTalleres Personal y otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-07-05', 'Charlas a Padres');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-08', 'Agua y Alcantarillado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-08-01', 'Basura y otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-10-09', 'Electricidad');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01', 'Telefono y Comunicaciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01-01', 'Cable');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01-02', 'Internet');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01-03', 'Recarga y otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01', 'Gastos de Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01-01', 'Cafe y Azucar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01-02', 'Uniformes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-01-03', 'Refrigerio');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-02', 'Data Chow - Fijo y Movible');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-04', 'Limpieza');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-04-01', 'Detergentes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-04-02', 'Utiles de limpieza');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-05', 'Mantenimiento Equipo de Transporte');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-05-01', 'Cambio de Aceite y Filtro');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-05-02', 'Revision General del Vehiculo');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-05-03', 'Pintura y Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-06', 'Combustibles y Lubricantes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-06-01', 'Gasoil Planta');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-06-02', 'Gas de Cosina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-06-03', 'Gasolina para Maquina de Limpieza');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-06-04', 'Otros ');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07', 'Mantenimiento Edificio  y Reparaciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-01', 'Pintura');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-02', 'Reparacion Plomeria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-03', 'Reparaciones Electricas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-04', 'Reparaciones de Herreria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-05', 'Reparaciones  de Ebanisteria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-06', 'Albanileria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-07', 'Reparaciones de Canchas Deportivas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-08', 'Reforzamiento y Remodelacion de Edificios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-07-09', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-08', 'Viajes Nacionales y Viativos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-08-01', '0,Viajes con el Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-08-02', 'Viaje con los Alumnos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-08-03', 'Viaticos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-08-04', 'Gastos de Flete');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-08-05', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-09', 'Viajes al Extranjero');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-09-01', 'Viajes con el Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-09-02', 'Viaje con los Alumnos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-09-03', 'Viaticos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-11-09-04', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01', 'Ayudas y Colaboraciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-01', 'Ayudas Familias de la Hermanas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-02', 'Ayudas a Personas Necesitadas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-03', 'Otras Ayudas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01', 'Regalos y Fiestas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-01', 'Celabraciones Congregacionales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-02', 'Celebraciones Comunitarias');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-03', 'Celebraciones con el Prtsonal Educativo');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-04', 'Celebraciones con Alumnos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-01-05', 'Otras Celebraciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-02', 'Obras y Fundacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-02-01', 'Fundacion de Obras');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-02-02', 'Sostenimineto Comunidades en el Extranjero');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-02-03', 'Ayudas Comunidades en nel Extranjero');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-02-04', 'Ayudas a Comunidades');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-03', 'Medicos y Medicinas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-03-01', 'Consultas Medicas y Excedentes Consultas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-03-02', 'Excedentes  EstudiosAnalisis y  Clinicas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-03-03', 'Medicamentos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-03-04', 'Otos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-04', 'Mantenimineto');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-04-01', 'Equipos Electronicos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-04-02', 'Equipos Electricos (FotocopiadorasTelevisorData Schow,');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-04-03', 'Planta Electrica eInversor');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-04-04', 'Mantenimiento Equipos de Oficina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-04-05', 'Muebles de Oficina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-04-06', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-05', 'Gastos Financieros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-05-01', 'Cargos BancariosChequerasy Manejo de Cuentas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-05-02', 'Impuesto 0,15%');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-05-03', 'Otros Cargos Bancarios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-06', 'Formacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-06-01', 'Etapa Inicial (Aspirantado)');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-06-02', 'Pre-Postulantado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-06-03', 'Noviciado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-06-04', 'Juniorado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-06-05', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-08', 'Impuestos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-08-01', 'Cartas de Exoneracion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-08-02', 'Otros Impuestos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-09', 'Alimentacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-09-01', 'Alimentos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-12-09-02', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-00', 'Donacion y Obsequio');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-00-01', 'Donacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-00-02', 'Obsequio');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-01', 'Escuela  Laboral');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-01-01', 'Otros Gastos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-02', 'Jardineria y Embellecimiento');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-02-01', 'Compra de Equipos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-02-02', 'Productos para Mantenimineto de Matas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-02-03', 'Materiales de Jardineria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-02-04', 'Compra de matas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-02-05', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-03', 'Inscripciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-03-01', 'Inscripciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-03-02', 'Devoluciones en Inscripcion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04', 'Gastos Hermanas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04-01', 'Vestidos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04-02', 'Zapatos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04-03', 'Ropa Interior');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04-04', 'Utiles de Aseo Personal');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04-05', 'Salida Hermanas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04-06', 'Hermanas Consejeras');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-04-07', 'Otros Gastos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-05', 'Utenciloios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-05-01', 'Utencilios de cocina');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-05-02', 'Utencilios de banos y habitaciones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-05-03', 'Utencilios de cafeteria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-05-04', 'Otros Utencilios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-06', 'Vacaciones y Divesiones');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-06-01', 'Vacaciones Hermanas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-06-02', 'Vacaciones Comunitarias');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-06-03', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-07', 'Gastos de Representacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-07-01', 'Representacion en  Eventos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-07-02', 'Representacion  en Congresos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-07-03', 'Otros Gastos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-08', 'Encuentros Congregacionales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-08-01', 'Asamblea de Evaluacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-08-02', 'Pre-Capitulo');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-08-03', 'Capitulo General');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-08-04', 'Reuniones Generales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-08-05', 'Otros Talleres');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-08-06', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-13-09', 'Otros Gastos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-00-05', 'Juegos Sanchinos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-00-06', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01', 'Obtencion y Legalizacion Documentos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01-01', 'Renovacion de Pasaportes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01-02', 'Renovacion de Visas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01-03', 'Prorroga de Pasaportes');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01-04', 'Renovacion Licencia de Conducir');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01-05', 'Obtencion de Documentos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01-06', 'Actas de Nacimineto y Legalizacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-01-07', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02', 'Cuotas Congregacionales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-01', '10% Caja General');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-02', '3era. Parte Saldo Anual');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-03', 'Hogar Madre Amadora');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-04', 'Seguro Retiro Hermanas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-05', 'Pensiones y Jubilaciones  Hermanas');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-06', 'Canonizacion Beato Ciriaco Sancha');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-07', 'Historia de la Congrecion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-08', 'Boletin Sanchino');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-09', 'Cuota de Formacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-02-10', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-03', 'Gastos Funerales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-03-01', 'Funeraria');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-03-02', 'Lapida y Entierro');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-03-03', 'Traslado al Lugar');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-03-04', 'Mantenimiento de Bobedas ');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-03-05', 'Gastos de Exumacion de Cadaveres');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-03-06', 'Otras');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-04', 'Publicidad y Propaganda');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-04-01', 'Propaganda Fundador');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-04-02', 'Propaganda Vocacional');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-04-03', 'Brochurs');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-04-04', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05', 'Sistema de Computos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-01', 'Compra del Sistema');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-02', 'Mantenimineto del Sistema');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-03', 'Compra de Equipos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-04', 'Compra de Materiles');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-05', 'Accesorio de Computos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-06', 'Actualizaciones dentro del Sistema');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-07', 'Licencias  de Funcionamiento');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-05-08', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-06', 'Animales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-06-01', 'Alimnento Animales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-06-02', 'Vacunas y Medicinas animales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-06-03', 'Utiles de bano y Parasitos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-06-04', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-07', 'Gastos Comunidades');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-07-01', 'EXTRANJERAS Y NACIONALEs');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-07-02', 'Cuba');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-07-03', 'Haiti y Otras');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-08', 'Gastos Financieros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-08-01', 'Gastos Bancarios');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-08-02', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-09', 'Monedas Extranjeras');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-09-01', 'Compra de Dolares');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-09-02', 'Compra de Euros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-14-09-03', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-00', 'Honorarios Profesionales');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-00-01', 'Igualas  Abogado');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-00-02', 'Iguala de Mantenimientos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-00-03', 'Auditorias');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-00-04', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-01', 'Gastos de Depreciacion');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-1501-01', 'Depreciacion de Edificio');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-1501-02', 'Depreciacion de Equipos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-1501-03', 'Depreciacion de Vehiculos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-1501-04', 'Depreciacion de Mobiliario');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-1501-05', 'Otros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-02', 'Polizas de Seguros');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-02-01', 'Seguro de Vehiculos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-02-02', 'Seguro de Vivienda');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-02-03', 'Seguro de Equipos');
INSERT INTO MHS.dbo.BaseAccountColege (Id, Code, Account) VALUES(NEWID(), '6-15-02-04', 'Otros');