using HCCS.Domain.Entities.Accounting;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Text;

namespace HCCS.Infrastructure.TableEntityConfiguration
{
    internal class AccountingAccountConfiguration : AuditableEntityTypeConfiguration<AccountingAccount>
    {
        public override void Configure(EntityTypeBuilder<AccountingAccount> builder)
        {
            builder.HasKey(x => x.Id);
            builder.HasData(
                        new AccountingAccount { Id = 1, TypeAcountingAcountId = 1, ReadOnly = false, AccountNumber = "1010", AccountName = "Caja" },
                        new AccountingAccount { Id = 2, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4106", AccountName = "Inscripciones" },
                        new AccountingAccount { Id = 3, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4107", AccountName = "Cuotas Estudiantiles" },
                        new AccountingAccount { Id = 4, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4108", AccountName = "Ventas" },
                        new AccountingAccount { Id = 5, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4109", AccountName = "Becas" },
                        new AccountingAccount { Id = 6, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4110", AccountName = "Aporte por trabajo hermanas" },
                        new AccountingAccount { Id = 7, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4111", AccountName = "Cafetería" },
                        new AccountingAccount { Id = 8, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4114", AccountName = "Cambio de divisas" },
                        new AccountingAccount { Id = 9, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4116", AccountName = "Cobro prestamos" },
                        new AccountingAccount { Id = 10, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4117", AccountName = "Pre- Matricula" },
                        new AccountingAccount { Id = 11, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4118", AccountName = "Venta de camiseta" },
                        new AccountingAccount { Id = 12, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4119", AccountName = "Certificados, sellos y record" },
                        new AccountingAccount { Id = 13, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4120", AccountName = "Recargo de mora" },
                        new AccountingAccount { Id = 14, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4202", AccountName = "Intereses bancarios" },
                        new AccountingAccount { Id = 15, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4203", AccountName = "Donaciones" },
                        new AccountingAccount { Id = 16, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4204", AccountName = "Subsidios" },
                        new AccountingAccount { Id = 17, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4205", AccountName = "Comisiones" },
                        new AccountingAccount { Id = 18, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4206", AccountName = "Otros ingresos" },
                        new AccountingAccount { Id = 19, TypeAcountingAcountId = 4, ReadOnly = false, AccountNumber = "4211", AccountName = "Taller de costura" },
                        new AccountingAccount { Id = 20, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "61", AccountName = "Egresos" },
                        new AccountingAccount { Id = 21, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6101", AccountName = "Templo y culto " },
                        new AccountingAccount { Id = 22, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6102", AccountName = "Sueldo personal" },
                        new AccountingAccount { Id = 23, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6103", AccountName = "Prestaciones laborales" },
                        new AccountingAccount { Id = 24, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6104", AccountName = "Seguro social" },
                        new AccountingAccount { Id = 25, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6105", AccountName = "Seguro medico" },
                        new AccountingAccount { Id = 26, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6106", AccountName = "Capacitación al personal" },
                        new AccountingAccount { Id = 27, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6107", AccountName = "Cursillos y retiros espirituales" },
                        new AccountingAccount { Id = 28, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6108", AccountName = "Agua, basura y alcantarillado" },
                        new AccountingAccount { Id = 29, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6109", AccountName = "Electricidad" },
                        new AccountingAccount { Id = 30, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6110", AccountName = "Teléfonos y comunicaciones" },
                        new AccountingAccount { Id = 31, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6111", AccountName = "refrigerios" },
                        new AccountingAccount { Id = 32, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6112", AccountName = "material didáctico" },
                        new AccountingAccount { Id = 33, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6113", AccountName = "suscripciones y compra de libros" },
                        new AccountingAccount { Id = 34, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6114", AccountName = "Utensilios de limpieza" },
                        new AccountingAccount { Id = 35, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6115", AccountName = "Mantenimiento equipo de transporte" },
                        new AccountingAccount { Id = 36, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6116", AccountName = "Combustible y lubricantes" },
                        new AccountingAccount { Id = 37, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6117", AccountName = "Mantenimiento edificio y reparaciones" },
                        new AccountingAccount { Id = 38, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6118", AccountName = "Viajes nacionales y viáticos" },
                        new AccountingAccount { Id = 39, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6119", AccountName = "Viajes Extranjero y viáticos" },
                        new AccountingAccount { Id = 40, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6120", AccountName = "Ayuda a familiares" },
                        new AccountingAccount { Id = 41, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6121", AccountName = "Otras Ayudas" },
                        new AccountingAccount { Id = 42, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6122", AccountName = "Regalos y fiestas" },
                        new AccountingAccount { Id = 43, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6123", AccountName = "Obras de apostolado y fundación" },
                        new AccountingAccount { Id = 44, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6124", AccountName = "Médicos y medicinas" },
                        new AccountingAccount { Id = 45, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6125", AccountName = "Mantenimiento de equipos" },
                        new AccountingAccount { Id = 46, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6126", AccountName = "Mantenimiento de muebles y equipos de oficinas" },
                        new AccountingAccount { Id = 47, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6127", AccountName = "Gastos financieros" },
                        new AccountingAccount { Id = 48, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6128", AccountName = "Formación(Noviciado-Postulando-Juniorado)" },
                        new AccountingAccount { Id = 49, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6129", AccountName = "Material de oficina" },
                        new AccountingAccount { Id = 50, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6130", AccountName = "Impuestos" },
                        new AccountingAccount { Id = 51, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6131", AccountName = "Alimentación" },
                        new AccountingAccount { Id = 52, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6132", AccountName = "Donación y obsequios" },
                        new AccountingAccount { Id = 53, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6133", AccountName = "Taller de costura" },
                        new AccountingAccount { Id = 54, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6134", AccountName = "Jardinería y embellecimiento" },
                        new AccountingAccount { Id = 55, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6135", AccountName = "Inscripciones" },
                        new AccountingAccount { Id = 56, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6136", AccountName = "Vestidos" },
                        new AccountingAccount { Id = 57, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6137", AccountName = "Otros gastos (utensilios)" },
                        new AccountingAccount { Id = 58, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6138", AccountName = "Vacaciones y diversiones" },
                        new AccountingAccount { Id = 59, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6139", AccountName = "Útiles de aseo personal" },
                        new AccountingAccount { Id = 60, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6140", AccountName = "Gastos de representación" },
                        new AccountingAccount { Id = 61, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6141", AccountName = "Gastos de becas" },
                        new AccountingAccount { Id = 62, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6142", AccountName = "Actividades culturales" },
                        new AccountingAccount { Id = 63, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6143", AccountName = "Obtención y legalización de documentos" },
                        new AccountingAccount { Id = 64, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6144", AccountName = "10 % caja general" },
                        new AccountingAccount { Id = 65, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6145", AccountName = "Tercera parte saldo anual" },
                        new AccountingAccount { Id = 66, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6146", AccountName = "Seguro retiro hermanas" },
                        new AccountingAccount { Id = 67, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6147", AccountName = "Casa madre amadora, hermanas mayores" },
                        new AccountingAccount { Id = 68, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6148", AccountName = "Canonización" },
                        new AccountingAccount { Id = 69, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6149", AccountName = "Gastos funerales" },
                        new AccountingAccount { Id = 70, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6150", AccountName = "publicidad y propaganda" },
                        new AccountingAccount { Id = 71, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6151", AccountName = "Consignaciones bancarias" },
                        new AccountingAccount { Id = 72, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6152", AccountName = "Sistema de cómputos" },
                        new AccountingAccount { Id = 73, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6153", AccountName = "Publicidad y propaganda" },
                        new AccountingAccount { Id = 74, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6154", AccountName = "Alimento de animales" },
                        new AccountingAccount { Id = 75, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6155", AccountName = "Cambio de divisas" },
                        new AccountingAccount { Id = 76, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6156", AccountName = "Préstamos" },
                        new AccountingAccount { Id = 77, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6157", AccountName = "Construcción" },
                        new AccountingAccount { Id = 78, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6159", AccountName = "Cambio de cheques" },
                        new AccountingAccount { Id = 79, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6160", AccountName = "Capitulo general" },
                        new AccountingAccount { Id = 80, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6162", AccountName = "Cuota cóndor y escuelas católicas" },
                        new AccountingAccount { Id = 81, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6163", AccountName = "Fondos operacionales" },
                        new AccountingAccount { Id = 82, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6169", AccountName = "Promociones vocacional" },
                        new AccountingAccount { Id = 83, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6174", AccountName = "Seguro de vehículo" },
                        new AccountingAccount { Id = 84, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6182", AccountName = "Ayudada a otras comunidades" },
                        new AccountingAccount { Id = 85, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6185", AccountName = "Asamblea y evaluaciones" },
                        new AccountingAccount { Id = 86, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6188", AccountName = "Reembolsos" },
                        new AccountingAccount { Id = 87, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6196", AccountName = "Honorarios profesionales" },
                        new AccountingAccount { Id = 88, TypeAcountingAcountId = 6, ReadOnly = false, AccountNumber = "6197", AccountName = "Regalía pascual" });
            
        }
    }
}
